-- Tear down schema (reverse dependency order)

DROP TABLE eam_assignment CASCADE CONSTRAINTS PURGE;
DROP TABLE eam_hardware CASCADE CONSTRAINTS PURGE;
DROP TABLE eam_software CASCADE CONSTRAINTS PURGE;
DROP TABLE eam_holder CASCADE CONSTRAINTS PURGE;
DROP TABLE eam_app_user CASCADE CONSTRAINTS PURGE;

COMMIT;
